ALTER TABLE public.waitlist_users
  ADD COLUMN IF NOT EXISTS gender TEXT,
  ADD COLUMN IF NOT EXISTS age INTEGER,
  ADD COLUMN IF NOT EXISTS sports TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS interests TEXT[] NOT NULL DEFAULT '{}';